clone:
    hg:
        image: plugins/hg
        environment:
            - HG_SHARE_POOL=/root/.cache/hg
        volumes:
            - cache:/root/.cache

pipeline:
    tox:
        image: ${IMAGE}
        environment:
            - CFLAGS=-O0
            - TOX_TESTENV_PASSENV=CFLAGS CI_BUILD_NUMBER CI_JOB_NUMBER CI_JOB_ID
        commands:
            - echo "[extensions]" >> /root/.hgrc
            - echo "hgext.share =" >> /root/.hgrc
            - echo "[share]" >> /root/.hgrc
            - echo "pool = /root/.cache/hg" >> /root/.hgrc
            - pip install tox pydot
            - tox -e "${TOXENV}"
        volumes:
             - cache:/root/.cache
    check_dist:
        image: ${IMAGE}
        commands:
            - pip install twine
            - python setup.py sdist
            - twine check dist/*
        volumes:
             - cache:/root/.cache
    check_doc:
        image: ${IMAGE}
        commands:
            - pip install sphinx
            - python -m sphinx -T -E -W -n -b html doc _build/html
            - python -m sphinx -T -E -W -n -b linkcheck doc _build
        volumes:
             - cache:/root/.cache

matrix:
    include:
        - IMAGE: python:3.7
          TOXENV: py37
        - IMAGE: python:3.8
          TOXENV: py38
        - IMAGE: python:3.9
          TOXENV: py39
        - IMAGE: python:3.10
          TOXENV: py310
