clone:
    hg:
        image: plugins/hg
        environment:
            - HG_SHARE_POOL=/root/.cache/hg
        volumes:
            - cache:/root/.cache

pipeline:
    tox:
        image: ${IMAGE}
        commands:
            - echo "[extensions]" >> /root/.hgrc
            - echo "hgext.share =" >> /root/.hgrc
            - echo "[share]" >> /root/.hgrc
            - echo "pool = /root/.cache/hg" >> /root/.hgrc
            - pip install tox pydot
            - tox -e "${TOXENV}"
        volumes:
             - cache:/root/.cache

matrix:
    include:
        - IMAGE: python:3.5
          TOXENV: py35
        - IMAGE: python:3.6
          TOXENV: py36
        - IMAGE: python:3.7
          TOXENV: py37
        - IMAGE: python:3.8
          TOXENV: py38
