clone:
    hg:
        image: plugins/hg
        environment:
            - HG_SHARE_POOL=/root/.cache/hg
        volumes:
            - cache:/root/.cache

pipeline:
    tox:
        image: ${IMAGE}
        commands:
            - echo -e "[repositories]\nhgext.share =\n[share]\npool = /root/.hgcache\n" >> /root/.hgrc
            - pip install tox pydot
            - tox -e "${TOXENV}"
        volumes:
             - cache:/root/.cache

matrix:
    include:
        - IMAGE: python:3.5
          TOXENV: py35
        - IMAGE: python:3.6
          TOXENV: py36
        - IMAGE: python:3.7
          TOXENV: py37
